#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import yaml from 'js-yaml';
import Ajv2020 from 'ajv/dist/2020.js';

const root=process.cwd();
const args=process.argv.slice(2); const command=args[0]||'help'; const json=args.includes('--json');
const readYaml=p=>yaml.load(fs.readFileSync(path.join(root,p),'utf8'));
const result=(ok,operation,data={},errors=[])=>{const out={ok,operation,exitCode:ok?0:1,paths:data.paths||[],...data,errors}; console.log(json?JSON.stringify(out,null,2):`${ok?'OK':'ERROR'} ${operation}\n${errors.map(e=>`- ${e}`).join('\n')}${data.summary?`\n${data.summary}`:''}`); process.exitCode=ok?0:1;};
function files(dir,ext){if(!fs.existsSync(dir))return[]; return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name),ext):(e.name.endsWith(ext)?[path.join(dir,e.name)]:[]));}
function validate(){const errors=[]; const ajv=new Ajv2020({allErrors:true,strict:false}); const schemas={}; for(const f of files(path.join(root,'schemas'),'.json')){const s=JSON.parse(fs.readFileSync(f)); if(s.$id){ajv.addSchema(s,s.$id);schemas[s.$id]=s;}}
 const ids=new Map(); for(const f of files(root,'.yaml')){if(f.includes('/vendor/')||f.includes('/node_modules/')||f.includes('/.opencode/skills/'))continue; let d;try{d=yaml.load(fs.readFileSync(f,'utf8'));}catch(e){errors.push(`${path.relative(root,f)}: YAML non valido: ${e.message}`);continue} if(d?.schema&&schemas[d.schema]){const v=ajv.getSchema(d.schema);if(!v(d)) errors.push(`${path.relative(root,f)}: ${ajv.errorsText(v.errors)}`);} const id=d?.identity?.id;if(id){if(ids.has(id))errors.push(`ID duplicato ${id}: ${ids.get(id)}, ${path.relative(root,f)}`);ids.set(id,path.relative(root,f));}}
 for(const sf of files(path.join(root,'planning/chapters'),'/skeleton.yaml')){void sf} // extension walker handled below
 for(const chapter of fs.readdirSync(path.join(root,'planning/chapters'))){const base=`planning/chapters/${chapter}`;if(!fs.existsSync(path.join(root,base,'skeleton.yaml')))continue;const s=readYaml(`${base}/skeleton.yaml`); const beats=s['beat-sequence']||[]; beats.forEach((id,i)=>{const p=`${base}/beats/${id}.yaml`;if(!fs.existsSync(path.join(root,p))){errors.push(`${base}/skeleton.yaml: riferimento mancante ${id}`);return;}const b=readYaml(p);if(b.identity['sequence-index']!==i+1)errors.push(`${p}: sequence-index errato`);const prev=i?beats[i-1]:null,next=i<beats.length-1?beats[i+1]:null;if(b.placement['previous-beat']!==prev||b.placement['next-beat']!==next)errors.push(`${p}: catena previous/next incoerente`);});
 const manuscript=path.join(root,`manuscript/chapters/${chapter}/chapter.md`); if(fs.existsSync(manuscript)){const body=fs.readFileSync(manuscript,'utf8').replace(/^#.*$/m,'').replace(/<!--[^]*?-->/g,'').trim(); if(body&&(s.status!=='approved'||beats.some(id=>readYaml(`${base}/beats/${id}.yaml`).identity.status!=='approved')))errors.push(`${path.relative(root,manuscript)}: prosa presente senza skeleton e contratti approvati`);}}
 const forbiddenRoots=['planning','manuscript','story','continuity','deliberations','reviews','proposals','decisions','knowledge','.studio','templates']; if(forbiddenRoots.some(d=>files(path.join(root,d),'').some(f=>f.split(path.sep).includes('scenes'))))errors.push('Directory scenes/ vietata');
 result(errors.length===0,'validate',{summary:`${ids.size} ID controllati; schemi, riferimenti, catene e gate verificati.`},errors);}
function status(){const state=readYaml('.studio/workflow-state.yaml');result(true,'project-status',{state:state.state,chapter:state.chapter,paths:['.studio/workflow-state.yaml'],summary:`${state.chapter}: ${state.state}`});}
function exportManuscript(){const state=readYaml('.studio/workflow-state.yaml');if(state.state!=='CHAPTER_ACCEPTED')return result(false,'export',{},['Esportazione bloccata: il capitolo attivo non è CHAPTER_ACCEPTED']); const chapters=files(path.join(root,'manuscript/chapters'),'.md').filter(f=>f.endsWith('chapter.md')).sort();fs.mkdirSync(path.join(root,'dist'),{recursive:true});const out='dist/manuscript.md';fs.writeFileSync(path.join(root,out),chapters.map(f=>fs.readFileSync(f,'utf8')).join('\n\n'));result(true,'export',{paths:[out],summary:`Esportati ${chapters.length} capitoli.`});}
function gate(name){const state=readYaml('.studio/workflow-state.yaml');const allowed={"beat-draft":['DRAFTING'],"beat-audit":['CONTRACT_AUDIT'],"beat-revise":['REVISION'],"canon-update":['CANON_UPDATE']}[name];if(allowed&&!allowed.includes(state.state))return result(false,name,{state:state.state},[`Transizione negata: ${name} richiede ${allowed.join(' o ')}`]);result(true,name,{state:state.state,summary:'Prerequisiti di stato soddisfatti; l’agente può produrre la proposta prevista.'});}
switch(command){case'validate':case'validate-project':validate();break;case'project-status':status();break;case'export':case'export-manuscript':exportManuscript();break;case'beat-draft':case'beat-audit':case'beat-revise':case'canon-update':gate(command);break;case'help':console.log('studio: validate|project-status|beat-draft|beat-audit|beat-revise|canon-update|export [--json]');break;default:result(true,command,{summary:'Comando delegato al relativo agente OpenCode; nessuna mutazione automatica.'});}
